{
 "title": "Wärmepumpe",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aussentemperatur",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Heizen",
     "select": [
      [
       { "params": [ "AUSSENTEMPERATUR" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Heizen",
     "select": [
      [
       { "params": [ "AUSSENTEMPERATUR" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heizwerte",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Heizen",
     "select": [
      [
       { "params": [ "ISTWERT HK1" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Heizen",
     "select": [
      [
       { "params": [ "SOLLWERT HK1" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Heizen",
     "select": [
      [
       { "params": [ "VORLAUFTEMPERATUR" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Heizen",
     "select": [
      [
       { "params": [ "VOLUMENSTROM" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aussentemperatur",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "temp",
     "measurement": "Heizen",
     "select": [
      [
       { "params": [ "AUSSENTEMPERATUR" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Verdichterzeiten",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Laufzeiten",
     "select": [
      [
       { "params": [ "ELEKTR. NE HEIZEN" ], "type": "field" }
      ],
      [
       { "params": [ "ELEKTR. NE WW" ], "type": "field" }
      ],
      [
       { "params": [ "VERDICHTER HEIZEN" ], "type": "field" }
      ],
      [
       { "params": [ "VERDICHTER WW" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauchswerte",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Leistungsaufnahme",
     "select": [
      [
       { "params": [ "P HEIZUNG TAG" ], "type": "field" }
      ],
      [
       { "params": [ "P WW TAG" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Lüftung",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Lueften",
     "select": [
      [
       { "params": [ "ABLUFT IST LÜFTERDREHZAHL" ], "type": "field" }
      ],
      [
       { "params": [ "ABLUFT SOLL VOLUMENSTROM" ], "type": "field" }
      ],
      [
       { "params": [ "ZULUFT IST LÜFTERDREHZAHL" ], "type": "field" }
      ],
      [
       { "params": [ "ZULUFT SOLL VOLUMENSTROM" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Prozesswerte",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Prozesswerte",
     "select": [
      [
       { "params": [ "FORTLUFT IST LÜFTERDREHZAHL" ], "type": "field" }
      ],
      [
       { "params": [ "FORTLUFT SOLL VOLUMENSTROM" ], "type": "field" }
      ],
      [
       { "params": [ "HEISSGASTEMPERATUR" ], "type": "field" }
      ],
      [
       { "params": [ "HOCHDRUCK" ], "type": "field" }
      ],
      [
       { "params": [ "NIEDERDRUCK" ], "type": "field" }
      ],
      [
       { "params": [ "VERDAMPFERTEMP." ], "type": "field" }
      ],
      [
       { "params": [ "VERFLÜSSIGERTEMP." ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Heizstufe",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Waermeerzeuger",
     "select": [
      [
       { "params": [ "HEIZSTUFE" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Wärmemengen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Waermemengen",
     "select": [
      [
       { "params": [ "WM HEIZEN SUMME" ], "type": "field" }
      ],
      [
       { "params": [ "WM HEIZEN TAG" ], "type": "field" }
      ],
      [
       { "params": [ "WM NE HEIZEN SUMME" ], "type": "field" }
      ],
      [
       { "params": [ "WM NE WW SUMME" ], "type": "field" }
      ],
      [
       { "params": [ "WM WRG SUMME" ], "type": "field" }
      ],
      [
       { "params": [ "WM WRG TAG" ], "type": "field" }
      ],
      [
       { "params": [ "WM WW SUMME" ], "type": "field" }
      ],
      [
       { "params": [ "WM WW TAG" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Warmwasser",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Wamwasser",
     "select": [
      [
       { "params": [ "WW-ISTTEMP." ], "type": "field" }
      ],
      [
       { "params": [ "WW-SOLLTEMP." ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leistungsaufnahme Summiert",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "alias": "Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Leistungsaufnahme_Summary",
     "select": [
      [
       { "params": [ "P HEIZUNG JAHR" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Warmwasser",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Leistungsaufnahme_Summary",
     "select": [
      [
       { "params": [ "P WW JAHR" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Webinterface der WP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stiebel Eltron Web",
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "content": "<div class=\"iframe_container\">\n  <iframe width=\"1024\" height=\"768\" src=\"http://servicewelt.lan\" frameborder=\"0\" allowfullscreen></iframe>\n</div>\n<div> <a href=\"https://servicewelt.stiebel-eltron.de/mobile/dashboard/dash.html\">Online Version</a> \n </div>\n"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Panel Title",
   "type": "natel-influx-admin-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}